UPDATE books SET title='Así es como se mata' WHERE id=28;
UPDATE books SET title='El Libro de Cocina Del Anarquista de la Mazmorra' WHERE id=29;
UPDATE books SET title='El Juicio Final de Carl' WHERE id=30;
UPDATE books SET title='Las recetas perdidas de la taberna Kamogawa' WHERE id=33;
UPDATE books SET saga='Crónica del asesino de reyes', saga_number=1, title='El nombre del viento' WHERE id=59;
UPDATE books SET saga=NULL, saga_number=NULL WHERE id=63;
UPDATE books SET saga=NULL, saga_number=NULL WHERE id=64;
UPDATE books SET title='Choque de reyes', author='George R.R. Martin', publisher='Gigamesh', publish_date='2012', pages=928, saga='Canción de hielo y fuego', saga_number=2 WHERE id=66;
UPDATE books SET saga='Canción de hielo y fuego', saga_number=4 WHERE id=67;
UPDATE books SET saga='Canción de hielo y fuego', saga_number=5 WHERE id=70;
UPDATE books SET saga='El Señor de los Anillos', saga_number=1 WHERE id=73;
UPDATE books SET saga='Dune', saga_number=1 WHERE id=85;
UPDATE books SET saga=NULL, saga_number=NULL WHERE id=90;
UPDATE books SET saga=NULL, saga_number=NULL WHERE id=92;
UPDATE books SET saga=NULL, saga_number=NULL WHERE id=99;
UPDATE books SET title='Entrevista con el vampiro' WHERE id=111;
UPDATE books SET saga='Resident Evil', saga_number=0 WHERE id=114;
UPDATE books SET saga=NULL, saga_number=NULL WHERE id=122;
UPDATE books SET saga=NULL, saga_number=NULL WHERE id=123;
UPDATE books SET saga=NULL, saga_number=NULL WHERE id=136;
UPDATE books SET saga=NULL, saga_number=NULL WHERE id=137;
