UPDATE books SET title='Así es como se mata (Un caso del comisario Mancini 1)' WHERE id=28;
UPDATE books SET title='El Libro de Cocina Del Anarquista de la Mazmorra (Carl el Mazmorrero 3) / the Dungeon Anarchist''s Cookbook' WHERE id=29;
UPDATE books SET title='El Juicio Final de Carl (Carl el Mazmorrero 2)' WHERE id=30;
UPDATE books SET title='Las recetas perdidas de la taberna Kamogawa (Taberna Kamogawa 3)' WHERE id=33;
UPDATE books SET saga='Crónica del asesino de reyes 1', saga_number=NULL, title='El nombre del viento / The Name of the Wind' WHERE id=59;
UPDATE books SET saga='El libro de bolsillo No. 5500 - Literatura', saga_number=NULL WHERE id=63;
UPDATE books SET saga='El libro de bolsillo No. 5536 - Literatura', saga_number=NULL WHERE id=64;
UPDATE books SET title='El mundo de hielo y fuego', author=NULL, publisher='Gilgamesh', publish_date='2015', pages=NULL, saga=NULL, saga_number=NULL WHERE id=66;
UPDATE books SET saga='Canción de hielo y fuego, 4', saga_number=NULL WHERE id=67;
UPDATE books SET saga='Canción de Hielo y Fuego, 5', saga_number=NULL WHERE id=70;
UPDATE books SET saga='Booket. Biblioteca J.R.R. Tolkien -- 5017/1', saga_number=NULL WHERE id=73;
UPDATE books SET saga='Dune (1)', saga_number=NULL WHERE id=85;
UPDATE books SET saga='Colección Booket', saga_number=NULL WHERE id=90;
UPDATE books SET saga='Novela No. 2189', saga_number=NULL WHERE id=92;
UPDATE books SET saga='Bestseller. Biblioteca Stephen King; 102/3', saga_number=NULL WHERE id=99;
UPDATE books SET title='Entrevista con el vampiro (Crónicas Vampíricas 1)' WHERE id=111;
UPDATE books SET saga='Resident evil ; 0', saga_number=NULL WHERE id=114;
UPDATE books SET saga='Contemporánea', saga_number=NULL WHERE id=122;
UPDATE books SET saga='Bestseller / Debolsillo', saga_number=NULL WHERE id=123;
UPDATE books SET saga='Millenium - Las 100 joyas del milenio No. 89 (Biblioteca El mundo)', saga_number=NULL WHERE id=136;
UPDATE books SET saga='Millenium - Las 100 joyas del milenio No. 42 (Biblioteca El mundo)', saga_number=NULL WHERE id=137;
